#!/bin/bash
echo "🎨 FlexIt Favicon Replacement Helper"
echo "======================================"
echo ""
echo "1. Download your logo from: http://localhost:3000/download-logo.html"
echo "2. Convert at: https://favicon.io/favicon-converter/"
echo "3. Extract the downloaded favicon_io.zip"
echo "4. Run this script from the extracted folder:"
echo ""
echo "   cd ~/Downloads/favicon_io"
echo "   bash /path/to/this/script/replace-favicon.sh"
echo ""
echo "Or manually copy these files to public/ folder:"
echo "   - favicon.ico"
echo "   - favicon-16x16.png"
echo "   - favicon-32x32.png"
echo "   - apple-touch-icon.png"
echo "   - android-chrome-192x192.png"
echo "   - android-chrome-512x512.png"
echo ""
echo "After copying, restart your dev server!"
